### ISSUE TITLE
/etc/nginx/conf.d/default.conf conflicts with /etc/nginx/conf.d/proxy.conf ?

### ISSUE THREAD

**Issue by alexjfisher** [openfrontier/nginx-docker#1]
I found I had to remove /etc/nginx/conf.d/default.conf from the container before the proxying would work.

Kind Regards,
Alex

**Comment by thinkernel** [comment]
Did you access your proxy container from localhost instead of remote?
Because default.conf only works when accessing from localhost.
Or did you change the ${HOST_NAME} value to your server's ip address?

**Comment by alexjfisher** [comment]
I was accessing the proxy remotely, via the docker host's external IP.
In the proxy.conf, I had server_name set to 'nginx-proxy' (the container's hostname).

I'm actually trying to setup puppet to install docker and launch the gerrit and nginx containers (instead of using your parent ci project's scripts).  I guess something must different somewhere.

**Comment by thinkernel** [comment]
How about make proxy.conf to overwrite default.conf like this one:
-v ~/nginx-docker/${PROXY_CONF}:/etc/nginx/conf.d/**default**.conf:ro

**Comment by thinkernel** [comment]
> In the proxy.conf, I had server_name set to 'nginx-proxy' (the container's hostname).

btw, I'm using the ip address of my server as the _server_name_ and access my container with the same ip address.
I'm not sure if just a hostname without a reverse DNS works.
Did you access your gerrit container with the url like _http://nginx-proxy/gerrit_ ?
Some examples of how to setup server_name can be found [here](http://nginx.org/en/docs/http/server_names.html).

**Comment by alexjfisher** [comment]
ah, ok.  That makes sense.  I guess the server_name has to match the name of the host, not the name of the container.  I'll give that a go.  Thanks.

**Comment by alexjfisher** [comment]
Yep, it has to match the name that the client used, but multiple names/IPs or regexes can be used.

Perhaps it wouldn't hurt to remove the default.conf in the Dockerfile.  Then _any_ server_name will work and it won't matter whether the client used the fqdn, hostname or IP address.

Personally, I might just do this in a child image.  I can add a static proxy.conf file (with hardcoded GERRIT_URI etc) and remove the need for using a volume with the container.

Thanks for your help,
Alex

**Comment by thinkernel** [comment]
You are welcome.
You can choose to mount a directory to /etc/nginx/conf.d. This will make the directory exactly as your local directory.
Since server_name in proxy.conf should be setup at nginx docker's start time, I don't know how to hard coding it into a docker images. Let me know if you can figure it out. :)

**Comment by alexjfisher** [comment]
If you remove default.conf, you can hard code proxy.cong server_name to anything and it won't matter.  It should then be your only virtual host and all requests will be handled there?

But that won't help if you want the GERRIT_URI etc configurable.  You'd still need to mount a volume for that.
